# Generated by Django 5.0.3 on 2024-04-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('link', 'Ссылка'), ('text', 'Текст')], max_length=4)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('subscribe', 'Подписаться на канал'), ('like', 'Поставить лайк'), ('comment', 'Написать комментарий'), ('watch', 'Посмотреть видео')], max_length=10)),
                ('link', models.URLField()),
                ('comment', models.TextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
        ),
    ]
