# Generated by Django 5.0.3 on 2024-04-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='main.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('text', 'Текст')], max_length=10),
        ),
    ]
