# Generated by Django 5.0.3 on 2024-12-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_page_content_type_page_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.CharField(default='link', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('channel', 'Подписаться на канал'), ('video', 'Поставить лайк на видео'), ('comment', 'Оставить комментарий'), ('watch', 'Посмотреть видео')], max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='link',
            field=models.URLField(default='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
