# Generated by Django 5.0.3 on 2024-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_page_content_type_alter_action_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_content',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='link_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
