# Generated by Django 5.0.3 on 2024-12-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_page_link_content_page_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='text_unlocking',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='text_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('text', 'Текст')], default='link', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
